name: Back-end Docker

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - "demo/demo/Dockerfile"
      - "demo/demo/pom.xml"
      - "demo/demo/src/**"
      - ".github/workflows/backend-docker.yml"
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
    paths:
      - "demo/demo/Dockerfile"
      - "demo/demo/pom.xml"
      - "demo/demo/src/**"
      - ".github/workflows/backend-docker.yml"

permissions:
  contents: read
  packages: write

jobs:
  # ตรวจ build บน PR (ไม่ push image)
  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v6
        with:
          context: ./demo/demo
          file: ./demo/demo/Dockerfile
          push: false

  # เมื่อ push เข้า main หรือสร้าง tag: build + push ไป GHCR
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./demo/demo
          file: ./demo/demo/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
